Bootstrap: docker
From: quay.io/biocontainers/blast:2.9.0--h20b68b9_1

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://www.andrew.cmu.edu/~icaoberg
    VERSION 2.9.0

%post
   rm /etc/resolv.conf

####################################################################################
